baseurl: "https://asso-out.fr"
title: "Out ! La culture dehors"
#SectionPagesMenu: "main"

languageCode: "fr"
theme: "casper-two"
canonifyurls: true
markup: "mmark"

paginate: 6
enableEmoji: true

disqusShortname: "asso-out-fr"
googleAnalytics: "UA-132500223-1"

params:
  subtitle: "La culture dehors !"
  keywords: "Out, out, asso out, association, asso, Lyon, association lyonnaise, asoociation, associations, culture, ouverture, cinéma, théâtre, interventions"
  images: "/uploads/logo.png" # OpenGraph image(s)
  image: "/uploads/logo.png"  # Twitter :image

  iconIco: "/uploads/favicon.ico"
  iconPng: "/uploads/favicon-152.png"
  thumbnailPost: "/uploads/thumbnail.png"
  thumbnailPage: "/uploads/thumbnail2.png"
 
  cover: "/uploads/logo.png"
  description: "L'association lyonnaise d'éveil par la culture !"
  customCSS: ["/my.css"]
  RSSLink: ""
  
  #twitterName: "faketryghost"
  fbName: "OutAsso"

  showSupport: true
  logo:         "/uploads/logo.png"
  # is it ever used???
  orgName: "OUT ! La culture dehors"
  orgWebsite: "https://www.asso-out.fr"
  orgDescription: "Out ! La culture dehors"

  # is it ever used???
  author: "Out !"
  authorAvatar: "/uploads/logo.png"
  authorDescription: "L'équipe"
  authorLocation: "Lyon, France" # not used
  authorWebsite: "//asso-out.fr" # not used

  #set it to caspertwo
  singleViewStyle: "caspertwo"

  # contentType types
  iconArticle: "/uploads/icons/article_emoji.png"
  iconEvent:   "/uploads/icons/alarm_emoji.png"

  # disqus comments
  disqusComments: true

permalinks:
  blog: "/blog/:year/:slug/"

#[[menu.main]]
# name: "Home"
# url: "/"
# weight: 100

menu:
    main:
        - name: "L'Asso"
          url: "/asso/"
          weight: 80
        - name: "Les membres"
          url: "/membres/"
          weight: 70
        - name: "Nos actions"
          url: "/actions/"
          weight: 60
        - name: "Contact"
          url: "/contact/"
          weight: 50
