baseurl: "https://asso-out.fr"
title: "Out ! La culture dehors"
#SectionPagesMenu: "main"
publishdir: "_site"
canonifyURLs: true

theme: "casper-two"
markup: "mmark"
defaultContentLanguage: "fr"
languageCode: "fr"
canonifyurls: true
paginate: 6

enableEmoji: true
disqusShortname: "asso-out-fr"
googleAnalytics: "UA-132500223-1"

params:
  description: "L'association lyonnaise d'éveil par la culture !"
  subtitle: "La culture dehors !"
  logo:     "/uploads/logo.png"
  email: "asso.out@gmail.com"
  keywords: "Out, out, asso out, association, asso, Lyon, association lyonnaise, asoociation, associations, culture, ouverture, cinéma, théâtre, interventions"
  images: [ "/uploads/logo.png", "/uploads/blog/2018-10-19-maison_mandela/1.jpg", "/uploads/blog/2018-04-22-vide_grenier/affiche.jpg" ] # OpenGraph image(s)
  image: "/uploads/logo.png"  # Twitter :image
  cover: "/uploads/logo.png"

  iconIco: "/uploads/favicon.ico"
  iconPng: "/uploads/favicon-152.png"
  thumbnailPost: "/uploads/thumbnail.png"
  thumbnailPage: "/uploads/thumbnail2.png"
 
  customCSS: ["/my.css"]
  RSSLink: ""
  
  # Structured Data
  structuredData: true
  legalName: "Out, la culture dehors"
  founders: 
  - name: "Noémie Fidélin"
    role: "Co-fondatrice"
  - name: "Mathilde Floch-Brenaud"
    role: "Co-fondatrice"
  orgName: "Out ! La culture dehors"

  #twitterName: "faketryghost"
  fbName: "OutAsso"

  showSupport: true

  # is it ever used???
  author: "Out !"
  authorAvatar: "/uploads/logo.png"

  # set it to caspertwo
  singleViewStyle: "caspertwo"

  # contentType types
  iconArticle: "/uploads/icons/article_emoji.png"
  iconEvent:   "/uploads/icons/alarm_emoji.png"

  # disqus comments
  disqusComments: true

permalinks:
  blog: "/blog/:year/:slug/"

#[[menu.main]]
# name: "Home"
# url: "/"
# weight: 100

menu:
    main:
        - name: "L'Asso"
          url: "/asso/"
          weight: 80
        - name: "Les membres"
          url: "/membres/"
          weight: 70
        - name: "Nos actions"
          url: "/actions/"
          weight: 60
        - name: "Contact"
          url: "/contact/"
          weight: 50
